change method name "withAddedRenderer -> withRenderer" and cleanup
yiisoft/yii-web pull request #281
Opened 2020-07-13 12:30 UTC by thenotsoft

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  |

2020-07-13 12:42 UTC, rustamwin approved these changes

2020-07-13 17:17 UTC, samdark requested changes

2020-07-13 17:17 UTC, samdark commented on src/ErrorHandler/ErrorCatcher.php
> +        return strtolower($mimeType);
Validation should not mutate the value.

2020-07-13 18:36 UTC, xepozz commented on src/ErrorHandler/ErrorCatcher.php
>          if ($rendererClass === '') {
What about to check that class exists instead?

2020-07-13 19:30 UTC, xepozz approved these changes

2020-07-13 19:30 UTC, xepozz commented on src/ErrorHandler/ErrorCatcher.php
> +        return strtolower($mimeType);
```suggestion
        return strtolower(trim($mimeType));
```

2020-07-14 11:46 UTC, xepozz approved these changes

2020-07-14 22:36 UTC, samdark approved these changes

2020-07-14 22:36 UTC, merged

2020-07-14 22:36 UTC, samdark commented
Thanks!