Move out user and clean dependencies
yiisoft/yii-web pull request #334
Opened 2020-11-04 17:03 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | #275

2020-11-05 11:20 UTC, samdark requested changes

2020-11-05 11:20 UTC, samdark commented on composer.json
> +        "yiisoft/validator": "^3.0@dev"
yiisoft/user should be added

2020-11-13 08:45 UTC, xepozz commented on composer.json
> +        "yiisoft/validator": "^3.0@dev"
Why?

2020-11-21 16:19 UTC, roxblnfk approved these changes
I also think there is no need to add a `user` as as dependency

2020-11-21 23:47 UTC, samdark approved these changes

2020-11-22 00:00 UTC, merged

2020-11-22 00:01 UTC, samdark commented
Finished and merged. Thank you!